version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: gossipia_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  gossipia:
    build: .
    container_name: gossipia_backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/gossipia
    depends_on:
      - mongo

volumes:
  mongo_data: